apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.placeholderSecret.name }}
  namespace: {{ .Values.placeholderSecret.namespace }}
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K